#default config.yml
defaultModifier: 2
defaultEffect: SLOW.1.5
fullEffects: ["INCREASE_DAMAGE.1.30", "SLOW.1.10"]
quickFill: CONFUSION.1.5

food: # The food bar modifiers for different foods (and items)
  BEETROOT: 10
  BLACK_DYE: 1
  COOKED_BEEF: 4
  COOKED_CHICKEN: 10
  COOKED_COD: 2
  COOKED_MUTTON: 10
  COOKED_PORKCHOP: 10
  COOKED_RABBIT: 2
  COOKED_SALMON: 2
  DRIED_KELP: 10
  GLISTERING_MELON_SLICE: 6 #todo [Same effects as suspicious stew. Randomized effect given when eaten if possible] [Only gives 3 hunger bars]
  MELON_SLICE: 4 #TODO gives strength 2 for 1 minute
  MUTTON: 10
  POTATO: 10
  PRISMARINE_SHARD: 2 #TODO gives dolphins grace for 5 seconds
  BEEF: 2
  CHICKEN: 2
  COD: 2
  PORKCHOP: 2 #TODO nausea for 5 seconds
  RABBIT: 2
  SALMON: 2
  SPIDER_EYE: 10 #No poison
  ROTTEN_FLESH: -8

effects:
  COOKED_BEEF: INCREASE_DAMAGE.2.60
  #GLISTERING_MELON_SLICE: ... #TODO Implement here.
  MELON_SLICE: INCREASE_DAMAGE.2.60
  PRISMARINE_SHARD: DOLPHINS_GRACE.1.5
  PORKCHOP: CONFUSION.1.5
  ROTTEN_FLESH: CONFUSION.1.10
