#default config.yml
debug: false

defaultModifier: 2
defaultEffect: SLOW.1.5
fullEffects: ["INCREASE_DAMAGE.1.30", "SLOW.1.10"]
quickFill: CONFUSION.1.5

food: # The food bar modifiers for different foods (and items)
  BEETROOT: 10
  BLACK_DYE: 1
  COOKED_BEEF: 4
  COOKED_CHICKEN: 10
  COOKED_COD: 2
  COOKED_MUTTON: 10
  COOKED_PORKCHOP: 10
  COOKED_RABBIT: 2
  COOKED_SALMON: 2
  DRIED_KELP: 10
  GLISTERING_MELON_SLICE: 6
  MELON_SLICE: 4
  MUTTON: 10
  POTATO: 10
  PRISMARINE_SHARD: 2
  BEEF: 2
  CHICKEN: 2
  COD: 2
  PORKCHOP: 2
  RABBIT: 2
  SALMON: 2
  SPIDER_EYE: 10
  ROTTEN_FLESH: -8

effects:
  COOKED_BEEF: INCREASE_DAMAGE.2.60
  MELON_SLICE: INCREASE_DAMAGE.2.60
  PRISMARINE_SHARD: DOLPHINS_GRACE.1.5
  PORKCHOP: CONFUSION.1.5
  ROTTEN_FLESH: CONFUSION.1.10
  GLISTERING_MELON_SLICE: [
    FIRE_RESISTANCE.1.4,
    BLINDNESS.1.6,
    SATURATION.1.1,
    JUMP.1.6,
    POISON.1.12,
    REGENERATION.1.8,
    NIGHT_VISION.1.5,
    WEAKNESS.1.5,
    WITHER.1.8
  ] #TODO Implement here.
